//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalacticShrine.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalacticShrine.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier non trouvé..
        /// </summary>
        public static string FichierNonTrouve {
            get {
                return ResourceManager.GetString("FichierNonTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de la clé ne peut pas être vide.
        /// </summary>
        public static string LeNomDeLaCleNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeNomDeLaCleNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de la section ne peut pas être vide.
        /// </summary>
        public static string LeNomDeLaSectionNePeutPasEtreVide {
            get {
                return ResourceManager.GetString("LeNomDeLaSectionNePeutPasEtreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplication de la clé &apos;{0}&apos; trouvée dans la section &apos;{1}.
        /// </summary>
        public static string MessageExceptionDuplicationDeLaCle {
            get {
                return ResourceManager.GetString("MessageExceptionDuplicationDeLaCle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lors de l&apos;analyse du numéro de ligne.
        /// </summary>
        public static string MessageExceptionErreurAnalyse0 {
            get {
                return ResourceManager.GetString("MessageExceptionErreurAnalyse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à avec la valeur.
        /// </summary>
        public static string MessageExceptionErreurAnalyse1 {
            get {
                return ResourceManager.GetString("MessageExceptionErreurAnalyse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;analyser le texte : &apos;{0}&apos;. Veuillez vous référer à l&apos;option de configuration &apos;{1}.{2}&apos; pour ignorer cette erreur..
        /// </summary>
        public static string MessageExceptionErreurFormatIni {
            get {
                return ResourceManager.GetString("MessageExceptionErreurFormatIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de valeur de section fermante. Veuillez consulter l&apos;option de configuration &apos;{0}.{1}&apos; pour ignorer cette erreur..
        /// </summary>
        public static string MessageExceptionErreurPasDeValeurDeSectionFermante {
            get {
                return ResourceManager.GetString("MessageExceptionErreurPasDeValeurDeSectionFermante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les propriétés doivent être contenues dans une section. Veuillez consulter l&apos;option de configuration &apos;{0}.{1}&apos; pour ignorer cette erreur..
        /// </summary>
        public static string MessageExceptionErreurProprietesHorsSection {
            get {
                return ResourceManager.GetString("MessageExceptionErreurProprietesHorsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriété trouvée sans clé. Veuillez consulter l&apos;option de configuration &apos;{0}.{1}&apos; pour ignorer cette erreur..
        /// </summary>
        public static string MessageExceptionErreurProprietesSansCle {
            get {
                return ResourceManager.GetString("MessageExceptionErreurProprietesSansCle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section dupliquée avec le nom &apos;{0}&apos;. Veuillez consulter l&apos;option de configuration &apos;{1}.{2}&apos; pour ignorer cette erreur..
        /// </summary>
        public static string MessageExceptionErreurSectionDupliqueeAvecLeNom {
            get {
                return ResourceManager.GetString("MessageExceptionErreurSectionDupliqueeAvecLeNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Demarrage: {0}, Fin: {1} Taille: {2}].
        /// </summary>
        public static string TamponDeChaineToString {
            get {
                return ResourceManager.GetString("TamponDeChaineToString", resourceCulture);
            }
        }
    }
}
