//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalacticShrine.TerminalExample.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalacticShrine.TerminalExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alignement du texte.
        /// </summary>
        public static string AlignementDuTexte {
            get {
                return ResourceManager.GetString("AlignementDuTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur n&apos;importe quelle touche pour continuer.
        /// </summary>
        public static string AppuyezNimporteQuelleTouche {
            get {
                return ResourceManager.GetString("AppuyezNimporteQuelleTouche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur la touche [Q] puis sur Entrée pour quitter.
        /// </summary>
        public static string AppuyezPourQuitter {
            get {
                return ResourceManager.GetString("AppuyezPourQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière-plan Avertissement.
        /// </summary>
        public static string ArrierePlanAvertissement {
            get {
                return ResourceManager.GetString("ArrierePlanAvertissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière-plan Danger.
        /// </summary>
        public static string ArrierePlanDanger {
            get {
                return ResourceManager.GetString("ArrierePlanDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière-plan Default.
        /// </summary>
        public static string ArrierePlanDefault {
            get {
                return ResourceManager.GetString("ArrierePlanDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière-plan Info.
        /// </summary>
        public static string ArrierePlanInfo {
            get {
                return ResourceManager.GetString("ArrierePlanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière plan Magenta.
        /// </summary>
        public static string ArrierePlanMagenta {
            get {
                return ResourceManager.GetString("ArrierePlanMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière-plan Primaire.
        /// </summary>
        public static string ArrierePlanPrimaire {
            get {
                return ResourceManager.GetString("ArrierePlanPrimaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière plan Sourdine.
        /// </summary>
        public static string ArrierePlanSourdine {
            get {
                return ResourceManager.GetString("ArrierePlanSourdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrière-plan Succes.
        /// </summary>
        public static string ArrierePlanSucces {
            get {
                return ResourceManager.GetString("ArrierePlanSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avertissemens.
        /// </summary>
        public static string Avertissemens {
            get {
                return ResourceManager.GetString("Avertissemens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleur.
        /// </summary>
        public static string Couleur {
            get {
                return ResourceManager.GetString("Couleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Danger.
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;-Gauche|Droite-&gt;.
        /// </summary>
        public static string DivisionGaucheDroite {
            get {
                return ResourceManager.GetString("DivisionGaucheDroite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Écrire.
        /// </summary>
        public static string Ecrire {
            get {
                return ResourceManager.GetString("Ecrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligne d&apos;écriture.
        /// </summary>
        public static string LigneEcriture {
            get {
                return ResourceManager.GetString("LigneEcriture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lignes de division (Linge de décoration).
        /// </summary>
        public static string LignesDeDivision {
            get {
                return ResourceManager.GetString("LignesDeDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lignes vides.
        /// </summary>
        public static string LignesVides {
            get {
                return ResourceManager.GetString("LignesVides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magenta.
        /// </summary>
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Primaire.
        /// </summary>
        public static string Primaire {
            get {
                return ResourceManager.GetString("Primaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sourdine.
        /// </summary>
        public static string Sourdine {
            get {
                return ResourceManager.GetString("Sourdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succes.
        /// </summary>
        public static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte aligné à droite.
        /// </summary>
        public static string TexteAligneADroite {
            get {
                return ResourceManager.GetString("TexteAligneADroite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte aligné à gauche.
        /// </summary>
        public static string TexteAligneAGauche {
            get {
                return ResourceManager.GetString("TexteAligneAGauche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte aligné au centre.
        /// </summary>
        public static string TexteAligneAuCentre {
            get {
                return ResourceManager.GetString("TexteAligneAuCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Avertissement.
        /// </summary>
        public static string TexteAvertissement {
            get {
                return ResourceManager.GetString("TexteAvertissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Danger.
        /// </summary>
        public static string TexteDanger {
            get {
                return ResourceManager.GetString("TexteDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Default.
        /// </summary>
        public static string TexteDefault {
            get {
                return ResourceManager.GetString("TexteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Info.
        /// </summary>
        public static string TexteInfo {
            get {
                return ResourceManager.GetString("TexteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Magenta.
        /// </summary>
        public static string TexteMagenta {
            get {
                return ResourceManager.GetString("TexteMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Primaire.
        /// </summary>
        public static string TextePrimaire {
            get {
                return ResourceManager.GetString("TextePrimaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Sourdine.
        /// </summary>
        public static string TexteSourdine {
            get {
                return ResourceManager.GetString("TexteSourdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Texte Succes.
        /// </summary>
        public static string TexteSucces {
            get {
                return ResourceManager.GetString("TexteSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thème Lumineux.
        /// </summary>
        public static string ThemeLumineux {
            get {
                return ResourceManager.GetString("ThemeLumineux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thème sombre.
        /// </summary>
        public static string ThemeSombre {
            get {
                return ResourceManager.GetString("ThemeSombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable &amp; valeurs.
        /// </summary>
        public static string VariableValeurs {
            get {
                return ResourceManager.GetString("VariableValeurs", resourceCulture);
            }
        }
    }
}
